// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRPCStatus() {
  return window['go']['app']['App']['CheckRPCStatus']();
}

export function FileNew(arg1) {
  return window['go']['app']['App']['FileNew'](arg1);
}

export function FileOpen(arg1) {
  return window['go']['app']['App']['FileOpen'](arg1);
}

export function FileQuit(arg1) {
  return window['go']['app']['App']['FileQuit'](arg1);
}

export function FileSave(arg1) {
  return window['go']['app']['App']['FileSave'](arg1);
}

export function FileSaveAs(arg1) {
  return window['go']['app']['App']['FileSaveAs'](arg1);
}

export function GetAppId() {
  return window['go']['app']['App']['GetAppId']();
}

export function GetAppPreferences() {
  return window['go']['app']['App']['GetAppPreferences']();
}

export function GetFilename() {
  return window['go']['app']['App']['GetFilename']();
}

export function GetLastTab(arg1) {
  return window['go']['app']['App']['GetLastTab'](arg1);
}

export function GetMarkdown(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetMarkdown'](arg1, arg2, arg3);
}

export function GetOrgPreferences() {
  return window['go']['app']['App']['GetOrgPreferences']();
}

export function GetPreference(arg1) {
  return window['go']['app']['App']['GetPreference'](arg1);
}

export function GetUserPreferences() {
  return window['go']['app']['App']['GetUserPreferences']();
}

export function GetWizardReturn() {
  return window['go']['app']['App']['GetWizardReturn']();
}

export function GetWizardState() {
  return window['go']['app']['App']['GetWizardState']();
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function IsReady() {
  return window['go']['app']['App']['IsReady']();
}

export function Logger(arg1) {
  return window['go']['app']['App']['Logger'](arg1);
}

export function SaveBounds(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveBounds'](arg1, arg2, arg3, arg4);
}

export function SetAppPreferences(arg1) {
  return window['go']['app']['App']['SetAppPreferences'](arg1);
}

export function SetHelpCollapsed(arg1) {
  return window['go']['app']['App']['SetHelpCollapsed'](arg1);
}

export function SetInitialized(arg1) {
  return window['go']['app']['App']['SetInitialized'](arg1);
}

export function SetLastTab(arg1, arg2) {
  return window['go']['app']['App']['SetLastTab'](arg1, arg2);
}

export function SetLastView(arg1) {
  return window['go']['app']['App']['SetLastView'](arg1);
}

export function SetMenuCollapsed(arg1) {
  return window['go']['app']['App']['SetMenuCollapsed'](arg1);
}

export function SetOrgPreferences(arg1) {
  return window['go']['app']['App']['SetOrgPreferences'](arg1);
}

export function SetRPC(arg1) {
  return window['go']['app']['App']['SetRPC'](arg1);
}

export function SetUserInfo(arg1, arg2) {
  return window['go']['app']['App']['SetUserInfo'](arg1, arg2);
}

export function SetUserPreferences(arg1) {
  return window['go']['app']['App']['SetUserPreferences'](arg1);
}
