// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {app} from '../models';
import {types} from '../models';

export function AppQuit(arg1:menu.CallbackData):Promise<void>;

export function CollapseHelp(arg1:boolean):Promise<void>;

export function CollapseMenu(arg1:boolean):Promise<void>;

export function FileNew(arg1:menu.CallbackData):Promise<void>;

export function FileOpen(arg1:menu.CallbackData):Promise<void>;

export function FileSave(arg1:menu.CallbackData):Promise<void>;

export function FileSaveAs(arg1:menu.CallbackData):Promise<void>;

export function GetFilename():Promise<app.FileStatus>;

export function GetFilenameOld():Promise<string>;

export function GetPreferences():Promise<types.AppPreferences>;

export function IsReady():Promise<boolean>;

export function IsReadyStr():Promise<string>;

export function SaveBounds(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetLastView(arg1:string):Promise<void>;
