// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {types} from '../models';

export function CheckRPCStatus():Promise<string>;

export function FileNew(arg1:menu.CallbackData):Promise<void>;

export function FileOpen(arg1:menu.CallbackData):Promise<void>;

export function FileQuit(arg1:menu.CallbackData):Promise<void>;

export function FileSave(arg1:menu.CallbackData):Promise<void>;

export function FileSaveAs(arg1:menu.CallbackData):Promise<void>;

export function GetAppId():Promise<types.Id>;

export function GetAppPreferences():Promise<types.AppPreferences>;

export function GetFilename():Promise<types.FileStatus>;

export function GetLastTab(arg1:string):Promise<string>;

export function GetMarkdown(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetOrgPreferences():Promise<types.OrgPreferences>;

export function GetPreference(arg1:string):Promise<string>;

export function GetUserPreferences():Promise<types.UserPreferences>;

export function GetWizardReturn():Promise<string>;

export function GetWizardState():Promise<types.WizardState>;

export function IsInitialized():Promise<boolean>;

export function IsReady():Promise<boolean>;

export function Logger(arg1:string):Promise<void>;

export function SaveBounds(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetAppPreferences(arg1:types.AppPreferences):Promise<void>;

export function SetHelpCollapsed(arg1:boolean):Promise<void>;

export function SetInitialized(arg1:boolean):Promise<void>;

export function SetLastTab(arg1:string,arg2:string):Promise<void>;

export function SetLastView(arg1:string):Promise<void>;

export function SetMenuCollapsed(arg1:boolean):Promise<void>;

export function SetOrgPreferences(arg1:types.OrgPreferences):Promise<void>;

export function SetRPC(arg1:string):Promise<void>;

export function SetUserInfo(arg1:string,arg2:string):Promise<void>;

export function SetUserPreferences(arg1:types.UserPreferences):Promise<void>;
