// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppQuit(arg1) {
  return window['go']['app']['App']['AppQuit'](arg1);
}

export function CollapseHelp(arg1) {
  return window['go']['app']['App']['CollapseHelp'](arg1);
}

export function CollapseMenu(arg1) {
  return window['go']['app']['App']['CollapseMenu'](arg1);
}

export function FileNew(arg1) {
  return window['go']['app']['App']['FileNew'](arg1);
}

export function FileOpen(arg1) {
  return window['go']['app']['App']['FileOpen'](arg1);
}

export function FileSave(arg1) {
  return window['go']['app']['App']['FileSave'](arg1);
}

export function FileSaveAs(arg1) {
  return window['go']['app']['App']['FileSaveAs'](arg1);
}

export function GetFilename() {
  return window['go']['app']['App']['GetFilename']();
}

export function GetFilenameOld() {
  return window['go']['app']['App']['GetFilenameOld']();
}

export function GetPreference(arg1) {
  return window['go']['app']['App']['GetPreference'](arg1);
}

export function GetPreferences() {
  return window['go']['app']['App']['GetPreferences']();
}

export function IsReady() {
  return window['go']['app']['App']['IsReady']();
}

export function IsReadyStr() {
  return window['go']['app']['App']['IsReadyStr']();
}

export function SaveBounds(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveBounds'](arg1, arg2, arg3, arg4);
}

export function SetLastView(arg1) {
  return window['go']['app']['App']['SetLastView'](arg1);
}
