// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetPreferences():Promise<config.Preferences>;

export function GetTemplateFolder():Promise<string>;

export function IsReady():Promise<boolean>;

export function SaveBounds(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetHelpOpen(arg1:boolean):Promise<void>;

export function SetLastView(arg1:string):Promise<void>;

export function SetMenuOpen(arg1:boolean):Promise<void>;
