// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollapseHelp(arg1) {
  return window['go']['main']['App']['CollapseHelp'](arg1);
}

export function CollapseMenu(arg1) {
  return window['go']['main']['App']['CollapseMenu'](arg1);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetTemplateFolder() {
  return window['go']['main']['App']['GetTemplateFolder']();
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function SaveBounds(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveBounds'](arg1, arg2, arg3, arg4);
}

export function SetLastView(arg1) {
  return window['go']['main']['App']['SetLastView'](arg1);
}
