name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build and Release
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          yarn install
      - name: Build App (Mac)
        if: runner.os == 'macOS'
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          wails build -platform darwin/universal
      - name: Build App (Linux)
        if: runner.os == 'Linux'
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          wails build -platform linux/amd64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trueblocks-codegen-${{ runner.os }}
          path: build/bin/*
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            build/bin/*
